site_name: TechDocs
site_url: https://docs.seekincs.com
site_author: Issac
site_description: "A documentation website about technology, including computer science, algorithms (ml, dl, cv, nlp) and so on."
repo_url: "https://github.com/seekincs/docs"
copyright: "TechDocs is licensed under the <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a>."

theme:
  name: null
  custom_dir: cinder
  colorscheme: xcode
  highlightjs: true

nav:
  - Home: index.md
  - Specimen: specimen.md

markdown_extensions:
  - admonition
  - toc:
      toc_depth: 6
      permalink: true
