site_name: TechDocs
site_url: https://docs.seekincs.com
site_author: Issac
site_description: "A documentation website about technology, including computer science, algorithms (ml, dl, cv, nlp) and so on."
repo_url: "https://github.com/seekincs/docs"
copyright: "TechDocs is licensed under the <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a>."

theme:
  name: null
  custom_dir: cinder
  colorscheme: xcode
  highlightjs: true

nav:
  - Computer Science:
      - Data Structure: cs/ds/index.md
      - Algorithm: cs/al/index.md
  - Resource: rs/index.md

markdown_extensions:
  - admonition
  - toc:
      toc_depth: 6
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # MathJax 支持
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
